server {
    listen 80;
    listen [::]:80;
    server_name _;

    root /var/www/pomochat;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|mp3)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }
}
